### ISSUE TITLE
ConsoleTest

### ISSUE THREAD

**Issue by konata233** [myhsp/CirTrojanBackend#1]

**Comment by konata233** [comment]
test
114514
1919810

**Comment by konata233** [comment]
> test
114514
1919810
**[*]** [2023-06-06 22:23:43] yjsnpi

**Comment by konata233** [comment]
> test
114514
1919810

**[*]** [2023-06-06 22:26:24] yjsnpi

**Comment by konata233** [comment]
我谔谔

**Comment by konata233** [comment]
> 我谔谔
>

**[*]** [2023-06-06 22:33:47] yjsnpi

**Comment by Creeper2333** [comment]
是我，混响男孩
我做东方鬼畜音mad好吗
### 不！

**Comment by Creeper2333** [comment]
*$ REPLY*> > 我谔谔
>

**[*]** [2023-06-06 22:33:47] yjsnpi

**[INFO]** [2023-06-06 22:44:34] yjsnpi

**Comment by Creeper2333** [comment]
> *$ REPLY*> > 我谔谔
>

**[*]** [2023-06-06 22:33:47] yjsnpi

**[INFO]** [2023-06-06 22:44:34] yjsnpi

**[INFO]** [2023-06-06 22:46:47] yjsnpi

**Comment by konata233** [comment]
是我，混响男孩
我做东方鬼畜音mad好吗

**Comment by konata233** [comment]
> 是我，混响男孩
我做东方鬼畜音mad好吗

**[INFO]** [2023-06-06 22:47:23] yjsnpi

**Comment by konata233** [comment]
calc
osk

**Comment by konata233** [comment]
> calc
osk

**[INFO]** [2023-06-06 22:48:50] yjsnpi

**Comment by konata233** [comment]
start https://github.com

**Comment by konata233** [comment]
> start https://github.com

**[INFO]** [2023-06-06 22:50:54] yjsnpi

**Comment by konata233** [comment]
osk

**Comment by Creeper2333** [comment]
**[INFO]** [2023-06-07 15:00:51]

**Comment by Creeper2333** [comment]
**[INFO]** [2023-06-07 15:00:51]

**Comment by Creeper2333** [comment]
osk

**[INFO]** [2023-06-07 15:03:31]

**Comment by Creeper2333** [comment]
osk

**[INFO]** [2023-06-07 15:03:31] 

**[INFO]** [2023-06-07 15:03:31]

**Comment by Creeper2333** [comment]
osk

**[INFO]** [2023-06-07 15:03:31] 

**[INFO]** [2023-06-07 15:03:31] 

**[INFO]** [2023-06-07 15:03:31]

**Comment by Creeper2333** [comment]
> osk

**[INFO]** [2023-06-07 15:06:45]

**Comment by Creeper2333** [comment]
> osk

**[INFO]** [2023-06-07 15:10:13] Success!

**Comment by Creeper2333** [comment]
> osk

**[INFO]** [2023-06-07 15:11:47] Success!

**Comment by Creeper2333** [comment]
> osk

**[INFO]** [2023-06-07 15:12:24] Success!

**Comment by Creeper2333** [comment]
> osk

**[INFO]** [2023-06-07 15:22:18] Success!

**Comment by konata233** [comment]
> osk

**[INFO]** [2023-06-07 15:22:18] Success!

**Comment by konata233** [comment]
calc
osk
taskmgr

**Comment by konata233** [comment]
> calc
osk
taskmgr

**[INFO]** [2023-06-07 15:22:18] Success!

**Comment by konata233** [comment]
internal
get_folder_content

**Comment by konata233** [comment]
> internal
get_folder_content

**[INFO]** [2023-06-07 15:26:27] ['.idea', 'config.conf', 'main.py', 'token.txt']

**Comment by Creeper2333** [comment]
> internal
get_folder_content

**[FATAL]** [2023-06-07 15:26:27] Program crashed while executing!
Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 306, in start
    raise Exception
Exception

**Comment by Creeper2333** [comment]
> None

**[FATAL]** [2023-06-07 15:26:27] Program crashed while executing!
Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 306, in start
    raise Exception
Exception

**Comment by Creeper2333** [comment]
> None

**[FATAL]** [2023-06-07 15:26:27] Program crashed while executing!
Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 306, in start
    raise Exception
Exception

**Comment by Creeper2333** [comment]
load_module
test
def run(*args):
    print('test')

**Comment by konata233** [comment]
load_module
test

**Comment by Creeper2333** [comment]
> load_module
test

**[FATAL]** [2023-06-07 15:37:38] Program crashed while executing!
Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 301, in start
    body = self.git.get_file_content(name) #'\n'.join(sequence[1:])
  File "D:\CirnoTrojanFrontEnd\main.py", line 27, in get_file_content
    return self.git.file_contents('{}.py'.format(module_name)).content
AttributeError: 'Repository' object has no attribute 'file_contents'

**Comment by konata233** [comment]
> load_module
test

**[INFO]** [2023-06-07 15:48:40] Module successfully loaded.

**Comment by konata233** [comment]
run_module
test

**Comment by Creeper2333** [comment]
> run_module
test

**[FATAL]** [2023-06-07 15:49:18] Program crashed while executing!
Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 276, in start
    if len(s.split) > 1:
TypeError: object of type 'builtin_function_or_method' has no len()

**Comment by Creeper2333** [comment]
> run_module
test

**[FATAL]** [2023-06-07 15:50:26] Module not found.

**Comment by Creeper2333** [comment]
> run_module
test

**[FATAL]** [2023-06-07 15:51:31] Module not found.

**Comment by konata233** [comment]
load_config
test

**Comment by konata233** [comment]
> load_config
test

**[INFO]** [2023-06-07 15:53:21] Config successfully updated.

**Comment by konata233** [comment]
run_module
test

**Comment by konata233** [comment]
> run_module
test

**[FATAL]** [2023-06-07 15:53:21] Module not found.

**Comment by konata233** [comment]
run_module
test

**Comment by Creeper2333** [comment]
> run_module
test

**[FATAL]** [2023-06-07 15:54:24] Module not found.

**Comment by Creeper2333** [comment]
> run_module
test

**[FATAL]** [2023-06-07 15:57:30] Program crashed while executing!
Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 288, in start
    r += render_notice(self.run_module(name, *args),
  File "D:\CirnoTrojanFrontEnd\main.py", line 231, in run_module
    ret = sys.modules[name].run(*args)
KeyError: 'test'

**Comment by Creeper2333** [comment]
> run_module
test

**[FATAL]** [2023-06-07 15:58:43] Program crashed while executing!
Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 288, in start
    r += render_notice(self.run_module(name, *args),
  File "D:\CirnoTrojanFrontEnd\main.py", line 231, in run_module
    ret = sys.modules['extensions.{}'.format(name)].run(*args)
KeyError: 'extensions.test'

**Comment by Creeper2333** [comment]
> run_module
test

**[FATAL]** [2023-06-07 16:04:17] Program crashed while executing!
Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 288, in start
    r += render_notice(self.run_module(name, *args),
  File "D:\CirnoTrojanFrontEnd\main.py", line 231, in run_module
    ret = sys.modules['extensions.{}'.format(name)].run(*args)
KeyError: 'extensions.test'

**Comment by konata233** [comment]
> run_module
test

**[INFO]** [2023-06-07 16:20:02] None

**Comment by konata233** [comment]
load_config
test requests

**Comment by konata233** [comment]
> load_config
test requests

**[INFO]** [2023-06-07 16:22:21] Config successfully updated.

**Comment by konata233** [comment]
load_module
test

**Comment by konata233** [comment]
> load_module
test

**[INFO]** [2023-06-07 16:22:21] Module successfully loaded.

**Comment by konata233** [comment]
run_module
test

**Comment by konata233** [comment]
> run_module
test

**[INFO]** [2023-06-07 16:22:21] <!DOCTYPE html><html><head><title>验证码_哔哩哔哩</title><meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,viewport-fit=cover"><meta name="spm_prefix" content="333.1291"><script type="text/javascrip

**Comment by konata233** [comment]
internal
install_pip_package request

**Comment by konata233** [comment]
> internal
install_pip_package request

**[INFO]** [2023-06-07 16:31:56] Success!

**Comment by konata233** [comment]
internal
get_folder_content

**Comment by konata233** [comment]
> internal
get_folder_content

**[INFO]** [2023-06-07 16:34:05] ['.idea', 'CirnoTrojanFrontEnd.zip', 'config.conf', 'extension', 'main.py', 'pip_loader.cmd', 'token.txt']

**Comment by konata233** [comment]
internal
__dict__

**Comment by konata233** [comment]
> internal
__dict__

**[FATAL]** [2023-06-07 17:13:06] Program crashed while executing!
Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 275, in start
    r += render_notice(self.exec_internal_cmd(func_name, *args),
  File "D:\CirnoTrojanFrontEnd\main.py", line 159, in exec_internal_cmd
    ret = self.__getattribute__(cmd_name)(*args)
TypeError: 'dict' object is not callable

**Comment by konata233** [comment]
internal
get_folder_content_rendered

**Comment by konata233** [comment]
> internal
get_folder_content_rendered

**[INFO]** [2023-06-07 17:15:13] 
- .idea
- CirnoTrojanFrontEnd.zip
- config.conf
- extension
- main.py
- pip_loader.cmd
- token.txt

**Comment by konata233** [comment]
internal
get_all_methods_rendered

**Comment by Creeper2333** [comment]
> internal
get_all_methods_rendered

**[INFO]** [2023-06-07 17:17:29] 
- update_interval
- current_folder
- config
- git

**Comment by konata233** [comment]
> internal
get_all_methods_rendered

**[INFO]** [2023-06-07 17:19:24] 
- update_interval
- current_folder
- config
- git
- __module__
- __init__
- exec_cmd
- exec_internal_cmd
- get_folder_content
- get_folder_content_rendered
- get_all_methods_rendered
- set_current_folder
- move_backward
- get_config
- set_config
- install_pip_package
- load_package
- init_module
- run_module
- start
- __dict__
- __weakref__
- __doc__
- __repr__
- __hash__
- __str__
- __getattribute__
- __setattr__
- __delattr__
- __lt__
- __le__
- __eq__
- __ne__
- __gt__
- __ge__
- __new__
- __reduce_ex__
- __reduce__
- __subclasshook__
- __init_subclass__
- __format__
- __sizeof__
- __dir__
- __class__

**Comment by konata233** [comment]
load_module
test

**Comment by konata233** [comment]
> load_module
test

**[INFO]** [2023-06-07 17:19:24] Module successfully loaded.

**Comment by konata233** [comment]
run_module
test http://bilibili.com

**Comment by konata233** [comment]
> run_module
test http://bilibili.com

**[INFO]** [2023-06-07 17:19:24] <!DOCTYPE html><html><head><title>验证码_哔哩哔哩</title><meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,viewport-fit=cover"><meta name="spm_prefix" content="333.1291"><script type="text/javascrip

**Comment by konata233** [comment]
run_module
test http://bilibili.com/ 2048

**Comment by konata233** [comment]
> run_module
test http://bilibili.com/ 2048

**[INFO]** [2023-06-07 17:19:24] <!DOCTYPE html><html><head><title>验证码_哔哩哔哩</title><meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,viewport-fit=cover"><meta name="spm_prefix" content="333.1291"><script type="text/javascrip

**Comment by konata233** [comment]
run_module
test http://baidu.com/ 2048

**Comment by Creeper2333** [comment]
> run_module
test http://baidu.com/ 2048

**[FATAL]** [2023-06-07 17:19:24] Program crashed while executing!
Traceback (most recent call last):
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\Program Files\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\Program Files\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 311, in start
    r += render_notice(self.run_module(name, *args),
  File "D:\CirnoTrojanFrontEnd\main.py", line 254, in run_module
    ret = sys.modules['extension.{}'.format(name)].run(*args)
  File "D:\CirnoTrojanFrontEnd\extension\test.py", line 4, in run
    return requests.post(args[0]).text[0:256]
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by konata233** [comment]
run_module
test http://www.baidu.com/ 2048

**Comment by konata233** [comment]
> run_module
test http://www.baidu.com/ 2048

**[INFO]** [2023-06-07 17:19:24] <html>
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<style data-for="result" id="css_result">
body{color:#333;background:#fff;padding:6px 0 0;margin:0;position:relative;min-width:900px}body,th,td,.p1,.p2{font-family:arial}p

**Comment by konata233** [comment]
run_module
test

**Comment by konata233** [comment]
> run_module
test

**[FATAL]** [2023-06-07 17:19:24] Program crashed while executing!
Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 311, in start
    r += render_notice(self.run_module(name, *args),
  File "D:\CirnoTrojanFrontEnd\main.py", line 254, in run_module
    ret = sys.modules['extension.{}'.format(name)].run(*args)
  File "D:\CirnoTrojanFrontEnd\extension\test.py", line 4, in run
    return requests.post(args[0]).text[0:256]
IndexError: tuple index out of range

**Comment by konata233** [comment]
run_module
test

**Comment by konata233** [comment]
> run_module
test

**[FATAL]** [2023-06-07 17:19:24] Program crashed while executing!
Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 311, in start
    r += render_notice(self.run_module(name, *args),
  File "D:\CirnoTrojanFrontEnd\main.py", line 254, in run_module
    ret = sys.modules['extension.{}'.format(name)].run(*args)
  File "D:\CirnoTrojanFrontEnd\extension\test.py", line 4, in run
    return requests.post(args[0]).text[0:256]
IndexError: tuple index out of range

**Comment by konata233** [comment]
load_module
test

**Comment by konata233** [comment]
> load_module
test

**[INFO]** [2023-06-07 17:19:24] Module successfully loaded.

**Comment by konata233** [comment]
run_module
test

**Comment by konata233** [comment]
> run_module
test

**[FATAL]** [2023-06-07 17:19:24] Program crashed while executing!
Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 311, in start
    r += render_notice(self.run_module(name, *args),
  File "D:\CirnoTrojanFrontEnd\main.py", line 254, in run_module
    ret = sys.modules['extension.{}'.format(name)].run(*args)
  File "D:\CirnoTrojanFrontEnd\extension\test.py", line 4, in run
    return('a'*2048)
IndexError: tuple index out of range

**Comment by konata233** [comment]
load_module
test

**Comment by konata233** [comment]
> load_module
test

**[INFO]** [2023-06-07 17:19:24] Module successfully loaded.

**Comment by konata233** [comment]
run_module
test http://baidu.com/ 2048

**Comment by Creeper2333** [comment]
> run_module
test http://baidu.com/ 2048

**[FATAL]** [2023-06-07 17:19:24] Program crashed while executing!
Traceback (most recent call last):
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\Program Files\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\Program Files\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CirnoTrojanFrontEnd\main.py", line 311, in start
    r += render_notice(self.run_module(name, *args),
  File "D:\CirnoTrojanFrontEnd\main.py", line 254, in run_module
    ret = sys.modules['extension.{}'.format(name)].run(*args)
  File "D:\CirnoTrojanFrontEnd\extension\test.py", line 4, in run
    return requests.get(args[0]).text[0:int(args[1])])
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\lzm20\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by konata233** [comment]
run_module
test http://www.baidu.com/ 2048

**Comment by konata233** [comment]
> run_module
test http://www.baidu.com/ 2048

**[INFO]** [2023-06-07 17:19:24] <html>
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<style data-for="result" id="css_result">
body{color:#333;background:#fff;padding:6px 0 0;margin:0;position:relative;min-width:900px}body,th,td,.p1,.p2{font-family:arial}p

**Comment by konata233** [comment]
load_module
test

**Comment by konata233** [comment]
> load_module
test

**[INFO]** [2023-06-07 17:19:24] Module successfully loaded.

**Comment by konata233** [comment]
run_module
test http://baidu.com/

**Comment by konata233** [comment]
> run_module
test http://baidu.com/

**[INFO]** [2023-06-07 17:19:24] <html>
<meta http-equiv="refresh" content="0;url=http://www.baidu.com/">
</html>

**Comment by konata233** [comment]
load_module
test

**Comment by konata233** [comment]
> load_module
test

**[INFO]** [2023-06-07 17:19:24] Module successfully loaded.

**Comment by konata233** [comment]
run_module
test http://www.baidu.com/

**Comment by konata233** [comment]
> run_module
test http://www.baidu.com/

**[INFO]** [2023-06-07 17:19:24] <html>
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<style data-for="result" id="css_result">
body{color:#333;background:#fff;padding:6px 0 0;margin:0;position:relative;min-width:900px}body,th,td,.p1,.p2{font-family:arial}p

**Comment by D1orama** [comment]
cmd /k echo test&&PAUSE

**Comment by NyonAneki** [comment]
> The token will expire on **2024/06/07**

**Comment by NyonAneki** [comment]
cmd /k echo test&&PAUSE

**Comment by NyonAneki** [comment]
> cmd /k echo test&&PAUSE

**[INFO]** [2023-06-07 18:05:39] Success!

**Comment by konata233** [comment]
calc

**Comment by NyonAneki** [comment]
> calc

**[INFO]** [2023-06-07 18:05:39] Success!

**Comment by NyonAneki** [comment]
> The token will expire on **2024/06/07**

**Comment by konata233** [comment]
calc

**Comment by NyonAneki** [comment]
> calc

**[INFO]** [2023-06-07 18:13:43] Success!

**Comment by NyonAneki** [comment]
> The token will expire on **2024/06/07**

**Comment by konata233** [comment]
calc

**Comment by NyonAneki** [comment]
> calc

**[INFO]** [2023-06-07 18:59:03] Success!

**Comment by D1orama** [comment]
osk

**Comment by NyonAneki** [comment]
> osk

**[INFO]** [2023-06-08 16:50:12] Success!

**Comment by D1orama** [comment]
run_module
test http://www.bilibili.com/

**Comment by NyonAneki** [comment]
> run_module
test http://www.bilibili.com/

**[FATAL]** [2023-06-08 16:50:12] Program crashed while executing!
Traceback (most recent call last):
  File "main.py", line 288, in start
    exec('import extension.{}'.format(name))
  File "<string>", line 1, in <module>
ImportError: No module named 'extension'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 291, in start
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined

**Comment by D1orama** [comment]
load_module
test

**Comment by NyonAneki** [comment]
> load_module
test

**[INFO]** [2023-06-08 16:50:12] Module successfully loaded.

**Comment by D1orama** [comment]
run_module
test http://www.bilibili.com/

**Comment by NyonAneki** [comment]
> run_module
test http://www.bilibili.com/

**[INFO]** [2023-06-08 16:50:12] <!DOCTYPE html><html><head><title>验证码_哔哩哔哩</title><meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,viewport-fit=cover"><meta name="spm_prefix" content="333.1291"><script type="text/javascript" src="//www.bilibili.com/gentleman/polyfill.js?features=Promise%2CObject.assign%2CString.prototype.includes%2CNumber.isNaN"></script>
    <script>
    window._riskdata_ = {
      'v_voucher': 'voucher_44038227-571a-4671-80ad-fbc879ef7b03'
    }
    </script>
    <script type="text/javascript" src="//s1.hdslb.com/bfs/seed/log/report/log-reporter.js"></script><link href="//s1.hdslb.com/bfs/static/jinkela/risk-captcha/css/risk-captcha.0.181e1aeb83624d178e84d15d8a3c7d7851cfbb1e.css" rel="stylesheet"></head><body><div id="biliMainHeader"></div><div id="risk-captcha-app"></div><script src="//s1.hdslb.com/bfs/seed/jinkela/risk-captcha-sdk/CaptchaLoader.js"></script><script type="text/javascript" src="//s1.hdslb.com/bfs/static/jinkela/risk-captcha/1.risk-captcha.181e1aeb83624d178e84d15d8a3c7d7851cfbb1e.js"></script><script type="text/javascript" src="//s1.hdslb.com/bfs/static/jinkela/risk-captcha/risk-captcha.181e1aeb83624d178e84d15d8a3c7d7851cfbb1e.js"></script></body></html>

**Comment by D1orama** [comment]
powershell

**Comment by NyonAneki** [comment]
> powershell

**[INFO]** [2023-06-08 16:50:12] Success!

**Comment by D1orama** [comment]
powershell

**Comment by NyonAneki** [comment]
> powershell

**[INFO]** [2023-06-08 16:56:01] Success!

**Comment by D1orama** [comment]
start calc

**Comment by NyonAneki** [comment]
> start calc


**[INFO]** [2023-06-08 16:56:01] Success!

**Comment by D1orama** [comment]
calc

**Comment by NyonAneki** [comment]
> calc

**[INFO]** [2023-06-08 16:56:01] Success!

**Comment by D1orama** [comment]
start calc

**Comment by NyonAneki** [comment]
> start calc

**[INFO]** [2023-06-08 16:56:01] Success!

**Comment by NyonAneki** [comment]
> The token will expire on **2024/06/07**

**Comment by NyonAneki** [comment]
> The token will expire on **2024/06/07**

**Comment by NyonAneki** [comment]
> The token will expire on **2024/06/07**

**Comment by NyonAneki** [comment]
> The token will expire on **2024/06/07**

**Comment by NyonAneki** [comment]
> The token will expire on **2024/06/07**

**Comment by NyonAneki** [comment]
> The token will expire on **2024/06/07**

**Comment by GutZuFusss** [comment]
SENF IST LECKER DARUM ESSEN WIR TÄGLICH VIEL SENF

DU KEK!
